### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by smrtrfszm** [Verseghy/website_frontend2#6]
# Features

- [ ] header
    - [x] basic
    - [x] drawer menu on mobile
    - [ ] big header animation
    - [ ] accessibility
- [ ] footer
    - [x] basic
    - [x] set links
        - [x] tankerületi központ
        - [x] email
        - [x] kréta
        - [x] kréta ügyintézés
        - [x] facebook
        - [x] github
    - [ ] accessibility
- [x] page renderer
    - [x] render page with styling
    - [x] sanitize html
        - [x] client side
        - [x] server side
- [ ] error handling
- [ ] home page
    - [x] header meta tags
    - [ ] featured posts
        - [ ] load
        - [ ] animate
        - [ ] accessibility
    - [x] load initial page of posts
    - [ ] "load more" button
    - [ ] preload on hover?
    - [x] banners
- [ ] posts page
    - [x] load post
    - [x] format date
    - [x] header meta tags
    - [ ] image carousel
        - [x] basic
        - [ ] fullscreen
        - [ ] pinch to zoom?
        - [x] filter out not image files (e.g. post id 385)
        - [x] accessibility
    - [x] cache post
    - [ ] accessibility
- [ ] information page
    - [x] load sidebar
    - [x] load initial page
    - [x] able to switch pages
    - [ ] make menu closeable on mobile
    - [ ] accessibility
- [ ] search
    - [x] search for term
    - [x] search for author
    - [x] search for label
    - [ ] advanced serach? (needs backend work)
    - [ ] accessibility
- [ ] canteen page
    - [x] load
    - [ ] accessibility
- [ ] pages
    - [x] load
    - [ ] accessibility
- [ ] events
    - [ ] load
    - [ ] popups
        - [ ] overflow
        - [ ] details
        - [ ] accessibility
    - [ ] accessibility
- [ ] misc pages
    - [x] colleagues
        - [ ] accessibility
    - [ ] authors
        - [ ] accessibility
    - [ ] diáktoll?
        - [ ] accessibility
- [ ] archive
    - [ ] accessibility
- [x] not found page
    - [x] header meta tags

# Other stuff

- [ ] huge layout shifts on initial loads
- [x] not working with multiple proxies (needs solidjs patch)
- [ ] setup ci
